import "styles/common/globals.scss";

import Context from "../context/Context";
import NavBar from "../component/NavBar";
import Head from "next/head";
export default function App({ Component, pageProps }) {
  return (
    <Context>
      <Head>
        <title>Create Next App</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="free-sticker-rubber-duck-4861674.png" />
      </Head>
      <main>
        <Component {...pageProps} />
      </main>
      {/* <NavBar /> */}
      {/* 로그인 구현하고나면 지울예정 */}
    </Context>
  );
}
